// Optional local asset packs, all git-ignored:
//  - legacy:    restored by scripts/salvage-legacy-assets.sh (backgrounds, BGM)
//  - ui:        imported by scripts/import-ui-assets.sh (home port, cut-in sprites, bands)
//  - portraits: generated by tools/portraitgen (one per card, public/portraits)
// Everything here must degrade gracefully when any pack is absent.
import { createContext, useContext, useEffect, useState, type ReactNode } from 'react'
import { audio } from './audio'
import type { Look } from './game'

const BASE = '/legacy'
const UI = `${BASE}/ui`
const PORTRAITS = '/portraits'

async function manifest<T>(url: string, version: number): Promise<T | undefined> {
  try {
    // Revalidate every time: re-importing art changes the manifest (and the
    // ?v= of each file in it), and a heuristically cached copy would keep
    // pointing at the old images.
    const res = await fetch(url, { cache: 'no-cache' })
    // Dev servers answer unknown paths with index.html, so insist on real JSON.
    const json = res.ok ? await res.json() : undefined
    return json?.version === version ? json : undefined
  } catch {
    return undefined
  }
}

// A card's full-body character art, as written by `go run ./cmd/portraits import`.
export interface Portrait {
  src: string
  w: number
  h: number
  // Face box as fractions of the image: x0, y0, x1, y1. Frames busts and map tokens.
  face?: [number, number, number, number]
}

interface PortraitManifest {
  version: 2
  portraits: Record<string, { file: string; w: number; h: number; face?: [number, number, number, number] | null }>
}

export interface Packs {
  legacy: boolean
  ui: boolean
  portraits: ReadonlyMap<string, Portrait>
}

export type Backdrop = 'title' | 'home' | 'standby' | 'battle' | 'result'

export function backdropUrl(scene: Backdrop, p: Packs): string | undefined {
  switch (scene) {
    case 'title':
      return p.legacy ? `${BASE}/img/title.png` : undefined
    case 'home':
      return p.ui ? `${UI}/home.jpg` : p.legacy ? `${BASE}/img/standby.jpg` : undefined
    case 'standby':
      return p.legacy ? `${BASE}/img/standby.jpg` : undefined
    case 'battle':
      return p.ui ? `${UI}/battle.jpg` : p.legacy ? `${BASE}/img/battle.jpg` : undefined
    case 'result':
      return p.legacy ? `${BASE}/img/result.jpg` : undefined
  }
}

// Character art for a card, if one has been generated. Without it ShipArt
// falls back to the ship silhouette.
export function portraitOf(look: Look, p: Packs): Portrait | undefined {
  return look.cardId ? p.portraits.get(look.cardId) : undefined
}

const NO_PACKS: Packs & { ready: boolean } = { legacy: false, ui: false, portraits: new Map(), ready: false }
const PacksContext = createContext(NO_PACKS)

export function AssetProvider({ children }: { children: ReactNode }) {
  const [packs, setPacks] = useState(NO_PACKS)
  useEffect(() => {
    Promise.all([
      manifest(`${BASE}/manifest.json`, 1),
      manifest(`${UI}/manifest.json`, 1),
      manifest<PortraitManifest>(`${PORTRAITS}/manifest.json`, 2),
    ]).then(([legacy, ui, portraits]) => {
      audio.legacyBgm = !!legacy
      const art = new Map<string, Portrait>()
      for (const [id, p] of Object.entries(portraits?.portraits ?? {})) {
        art.set(id, { src: `${PORTRAITS}/${p.file}`, w: p.w, h: p.h, face: p.face ?? undefined })
      }
      setPacks({ legacy: !!legacy, ui: !!ui, portraits: art, ready: true })
    })
  }, [])
  return <PacksContext.Provider value={packs}>{children}</PacksContext.Provider>
}

export const useAssets = () => useContext(PacksContext)
