// Optional local asset packs, all git-ignored:
//  - legacy:    restored by scripts/salvage-legacy-assets.sh (portraits, banners, BGM)
//  - ui:        imported by scripts/import-ui-assets.sh (home port, cut-in sprites, bands)
//  - portraits: generated by scripts/portraits_colab.ipynb (one per card, public/portraits)
// Everything here must degrade gracefully when any pack is absent.
import { createContext, useContext, useEffect, useState, type ReactNode } from 'react'
import { audio } from './audio'
import type { Look } from './game'
import type { ShipClass } from './types'

const BASE = '/legacy'
const UI = `${BASE}/ui`
const PORTRAITS = '/portraits'

async function manifest(url: string): Promise<{ version: number; cards?: string[] } | undefined> {
  try {
    const res = await fetch(url)
    // Dev servers answer unknown paths with index.html, so insist on real JSON.
    const json = res.ok ? await res.json() : undefined
    return json?.version === 1 ? json : undefined
  } catch {
    return undefined
  }
}

export interface Packs {
  legacy: boolean
  ui: boolean
  // Card ids that have a generated portrait.
  portraits: ReadonlySet<string>
}

export type Backdrop = 'title' | 'home' | 'standby' | 'battle' | 'result'

export function backdropUrl(scene: Backdrop, p: Packs): string | undefined {
  switch (scene) {
    case 'title':
      return p.legacy ? `${BASE}/img/title.png` : undefined
    case 'home':
      return p.ui ? `${UI}/home.jpg` : p.legacy ? `${BASE}/img/standby.jpg` : undefined
    case 'standby':
      return p.legacy ? `${BASE}/img/standby.jpg` : undefined
    case 'battle':
      return p.ui ? `${UI}/battle.jpg` : p.legacy ? `${BASE}/img/battle.jpg` : undefined
    case 'result':
      return p.legacy ? `${BASE}/img/result.jpg` : undefined
  }
}

// Classes the legacy pack has character art for.
export const PORTRAIT_CLASSES: ShipClass[] = ['battleship', 'destroyer', 'submarine']
// The starter cards are the original three characters, so they wear the legacy art.
export const PORTRAIT_CARDS: Record<string, ShipClass> = {
  bb_kurogane: 'battleship',
  dd_asanagi: 'destroyer',
  ss_senryu: 'submarine',
}

export interface Portrait {
  src: string
  // Token face framing: a legacy class or 'gen' (see .ship-token in styles.css).
  face: ShipClass | 'gen'
}

// Character art for a card: the legacy starters first, then generated
// portraits. Undefined means ShipArt falls back to the ship silhouette.
export function portraitOf(look: Look, p: Packs): Portrait | undefined {
  const id = look.cardId
  if (!id) return undefined
  const legacyCls = p.legacy ? PORTRAIT_CARDS[id] : undefined
  if (legacyCls) return { src: assets.portrait(legacyCls), face: legacyCls }
  if (p.portraits.has(id)) return { src: `${PORTRAITS}/${id}.png`, face: 'gen' }
  return undefined
}

export const assets = {
  portrait: (c: ShipClass) => `${BASE}/img/ship/${c}.png`,
  sunk: `${BASE}/img/sunk.png`,
  explosion: `${BASE}/img/explosion.png`,
}

const NO_PACKS: Packs & { ready: boolean } = { legacy: false, ui: false, portraits: new Set(), ready: false }
const PacksContext = createContext(NO_PACKS)

export function AssetProvider({ children }: { children: ReactNode }) {
  const [packs, setPacks] = useState(NO_PACKS)
  useEffect(() => {
    Promise.all([manifest(`${BASE}/manifest.json`), manifest(`${UI}/manifest.json`), manifest(`${PORTRAITS}/manifest.json`)]).then(([legacy, ui, portraits]) => {
      audio.legacyBgm = !!legacy
      setPacks({ legacy: !!legacy, ui: !!ui, portraits: new Set(portraits?.cards ?? []), ready: true })
    })
  }, [])
  return <PacksContext.Provider value={packs}>{children}</PacksContext.Provider>
}

export const useAssets = () => useContext(PacksContext)
